image: rust:1.50

stages:
  - code-style
  - build
  - testing


code-style:
  stage: code-style
  before_script:
    - rustup component add rustfmt
  script:
    - rustfmt --check --config-path . ./server/src/main.rs
    - rustfmt --check --config-path . ./rendering/src/lib.rs 
    - rustfmt --check --config-path . ./rendering_wasm/src/lib.rs


build-rendering:
  stage: build
  script:
    - cd rendering
    - cargo build --release

test-rendering:
  stage: testing
  script:
    - cd rendering
    - cargo test --release --verbose -- point_at_parameter render_background render_sphere_color render_sphere_normals render_antialiasing camera_positionable
