[package]
name = "mandelbrot_gen"
version = "0.1.0"
authors = ["Alvaro Sanchez <a.sanchez@smartreporting.de>"]
edition = "2018"

[dependencies]
num = "0.2.0"
image = "0.22.3"
ndarray = "0.12.0"
docopt = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
rendering = { path = "../../rendering" }
