[package]
name = "rendering"
version = "0.1.0"
authors = ["Alvaro Sanchez <a.sanchez@smartreporting.de>"]
edition = "2018"

[lib]
name = "rendering_c_abi"
crate-type = ["dylib", "cdylib"]
#crate-type = ["dylib"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
ndarray = "0.12.0"
rand = "0.7.2"
wasm-bindgen = "0.2"



# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.2"
image = "0.22.3"

#[profile.release]
## Tell `rustc` to optimize for small code size.
#opt-level = "s"
