[package]
name = "server"
version = "0.1.0"
authors = ["Alvaro Sanchez <asmoscosa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
rocket = "0.4.7"
rendering = { path = "../rendering" }
